#!/bin/sh
# Renders the trusted-proxy config, then hands off to supervisord.
#
# Stackyard runs its own nginx inside the container, so when it sits behind
# another reverse proxy (Nginx Proxy Manager, Caddy, Traefik) the inner nginx
# sees that proxy as the client. Every request then looks like it came from one
# address, and per-client rate limiting degrades to one shared bucket.
#
# TRUSTED_PROXY names where the front proxy is. nginx then takes the real client
# address from the forwarding headers those proxies already send by default, so
# nothing has to be configured on their side and nothing downstream has to parse
# a header chain.
#
#   TRUSTED_PROXY=172.18.0.0/16
#   TRUSTED_PROXY="172.18.0.0/16 10.0.0.5"
#
# Unset means trust nothing, which is correct for direct access.
set -eu

# Overridable so the rendering can be tested without writing into /etc.
REALIP_CONF="${REALIP_CONF:-/etc/nginx/http.d/realip.conf}"

{
  echo "# Generated by docker-entrypoint.sh from TRUSTED_PROXY. Do not edit."
  if [ -n "${TRUSTED_PROXY:-}" ]; then
    for cidr in $(echo "$TRUSTED_PROXY" | tr ',' ' '); do
      echo "set_real_ip_from $cidr;"
    done
    echo "real_ip_header X-Forwarded-For;"
    # Walk the chain from the right, skipping addresses we trust, so the real
    # client is found even with several proxies in front.
    echo "real_ip_recursive on;"
  else
    echo "# TRUSTED_PROXY not set: forwarding headers are not trusted."
  fi
} > "$REALIP_CONF"

# Fail fast and loudly rather than starting with a config nginx will reject.
nginx -t

# supervisord always exits 0 on SIGTERM, including the SIGTERM that
# scripts/exit-on-fatal.py sends when a program can no longer be started. The
# marker carries that failure out as the container's exit code, so a dead API
# reads as a failure rather than a normal shutdown and `restart: on-failure`
# behaves the same as `unless-stopped` here.
MARKER="${SUPERVISOR_FATAL_MARKER:-/tmp/stackyard-fatal}"
rm -f "$MARKER"

# Run in the background rather than exec, so this script survives to read the
# marker afterwards. That means signals no longer reach supervisord on their
# own, and without forwarding a `docker stop` would kill this shell and leave
# supervisord running until the kill timeout, with nothing shut down cleanly.
"$@" &
child=$!
trap 'kill -TERM "$child" 2>/dev/null' TERM INT

# `wait` returns early when a signal is handled, so wait again for the real exit.
wait "$child"
status=$?
if [ "$status" -gt 128 ]; then
  wait "$child" 2>/dev/null
  status=$?
fi

if [ -f "$MARKER" ]; then
  echo "stackyard: $(cat "$MARKER") could not be started; exiting so the container is restarted" >&2
  rm -f "$MARKER"
  exit 1
fi

exit "$status"
