/* The container must refuse to start on a config nginx rejects.

   The trusted-proxy config is written at container start from TRUSTED_PROXY, so
   it is the one piece of nginx configuration the image build cannot validate: a
   value that renders into something nginx will not accept only exists on the
   user's machine. docker-entrypoint.sh checks it there and aborts.

   Losing that check would not fail any other test. The container would come up,
   nginx would refuse the bad file, and the site would be half-configured with
   the failure buried in the container log.

   The check is exercised with a stand-in for nginx, since there is none in the
   test environment. What is being tested is the entrypoint's reaction to a
   rejected config, not nginx's parser. */

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const { tmpDir } = require('../test-support/tmp');

const ENTRYPOINT = path.join(__dirname, '../../docker-entrypoint.sh');

/* Runs the real entrypoint with a stand-in nginx and a handoff command that
   leaves a trace, so "did it get that far" is decidable.
   @returns {{ status: number, started: boolean, checked: string|null }} */
function run({ nginxExit = 0, env = {} } = {}) {
  const dir = tmpDir('entrypoint');
  const realip = path.join(dir, 'realip.conf');
  const started = path.join(dir, 'started');
  /* What the stand-in saw when it was asked to check, which is how the test
     knows the check ran against the rendered file rather than before it. */
  const seen = path.join(dir, 'seen');
  const binDir = path.join(dir, 'bin');
  fs.mkdirSync(binDir);

  fs.writeFileSync(path.join(binDir, 'nginx'),
    `#!/bin/sh\ncat "${realip}" > "${seen}" 2>/dev/null\nexit ${nginxExit}\n`);
  fs.chmodSync(path.join(binDir, 'nginx'), 0o755);

  let status = 0;
  try {
    execFileSync('sh', [ENTRYPOINT, 'sh', '-c', `touch "${started}"`], {
      env: {
        PATH: `${binDir}:${process.env.PATH}`,
        REALIP_CONF: realip,
        SUPERVISOR_FATAL_MARKER: path.join(dir, 'fatal'),
        ...env,
      },
      stdio: 'pipe',
    });
  } catch (e) {
    status = e.status;
  }

  return {
    status,
    started: fs.existsSync(started),
    checked: fs.existsSync(seen) ? fs.readFileSync(seen, 'utf8') : null,
  };
}

/* The control. Without this, a test that only asserts failure would still pass
   if the entrypoint were broken in some entirely different way. */
test('a config nginx accepts starts normally', () => {
  const r = run();
  assert.equal(r.status, 0);
  assert.ok(r.started, 'the handoff command should have run');
});

test('a config nginx rejects stops the container from starting', () => {
  const r = run({ nginxExit: 1 });
  assert.notEqual(r.status, 0, 'the entrypoint must exit non-zero');
  assert.ok(!r.started,
    'nothing may be started once the config has been rejected');
});

/* Checking before rendering would validate the previous file, or the shipped
   placeholder, and pass on a TRUSTED_PROXY value nginx cannot accept. */
test('the check runs against the config that was just rendered', () => {
  const r = run({ env: { TRUSTED_PROXY: '172.18.0.0/16' } });
  assert.ok(r.checked, 'the config was not checked at all');
  assert.match(r.checked, /set_real_ip_from 172\.18\.0\.0\/16;/);
});

test('the rendered config is checked even when no proxy is trusted', () => {
  const r = run();
  assert.ok(r.checked, 'the config was not checked at all');
  assert.match(r.checked, /Generated by docker-entrypoint\.sh/);
});
